package_assets:         off          # (on, off, always)
embed_assets:           off          # (on, off, datauri)
compress_assets:        on          # (on, off)
gzip_assets:            on          # (on, off)
#template_function:      _.template  # (defaults to the built-in micro-templating)
#css_compressor_options: line_break

#javascripts:
#  workspace:
#    - public/javascripts/*.js
#  vendor:
#    - public/javascripts/vendor/*.js
#    - public/javascripts/vendor/fancybox/*.js
#    - public/javascripts/vendor/linkify/1.0/*.js
#    
stylesheets:
  common:
    - public/stylesheets/local/*.css
