package_assets:         on          # (on, off, always)
embed_assets:           on          # (on, off, datauri)
compress_assets:        on          # (on, off)
gzip_assets:            on          # (on, off)

#javascripts:
#  workspace:
#    - public/javascripts/*.js
#  vendor:
#    - public/javascripts/vendor/*.js
#    - public/javascripts/vendor/fancybox/*.js
#    - public/javascripts/vendor/linkify/1.0/*.js
#    
stylesheets:
  common:
    - public/stylesheets/*.css
  vendor:
    - public/javascripts/vendor/fancybox/jquery.fancybox-1.3.4.css
