apps:
  # map the environments to your desired heroku app names
  # for example,
  #   production: awesomeapp
  # would create the RACK_ENV=production
  # and deploy to http://awesomeapp.heroku.com
  production: ffflourishtest
  staging: ffflourishtest-staging
  legacy: ffflourishtest-legacy

stacks:
  # choose the stacks you want to use for each app.
  # the all: setting sets the default
  all: bamboo-mri-1.9.2

  # override on a per environment basis
  #legacy: bamboo-ree-1.8.7

config:
  # choose the configuration settings for all environments
  all:
    BUNDLE_WITHOUT: "test development"
    CONFIG_VAR1: "config1"
    CONFIG_VAR2: "config2"

  # you can also override configuration settings for each environment
  production:
    CONFIG_VAR1: "config1-production"
  staging:
    CONFIG_VAR1: "config1-staging"

collaborators:
  all:
    - "robert.brackett3@gmail.com"

domains:
  production:
    - "ffflourishtest.heroku.com"

addons:
  all:
    # add any other addons here
    - bundles:single
    - mongohq:free
    - shareddatabase:5mb

  production:
    # list production env specific addons here
